// User Actions
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// Classrooms Actions
export const FETCH_ALL_CLASSROOMS = "FETCH_ALL_CLASSROOMS";
export const FETCH_CLASSROOM = "FETCH_CLASSROOM";
export const CLASSROOMS_LOADING = "CLASSROOMS_LOADING";
export const CLASSROOM_CREATE = "CLASSROOM_CREATE";
export const CLASSROOM_UPDATE = "CLASSROOM_UPDATE";
export const CLASSROOM_DELETE = "CLASSROOM_DELETE";

// Students Actions
export const FETCH_ALL_STUDENTS = "FETCH_ALL_STUDENTS";
export const FETCH_STUDENT_BY_ID = "FETCH_STUDENT_BY_ID";

// Enrolled Students Actions
export const FETCH_ENROLLED_STUDENTS = "FETCH_ENROLLED_STUDENTS";
export const ENROLL_STUDENT = "ENROLL_STUDENT";
